/**
 * This file was generated by the Jeddict
 */
package models;

import java.time.LocalDateTime;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

/**
 * @author Jonas
 */
@Entity

@NamedQueries({
@NamedQuery(name = "MovieRating.findAll", query = "SELECT r FROM MovieRating r"),
@NamedQuery(name = "MovieRating.findById", query = "SELECT r FROM MovieRating r WHERE r.id=:id"),
@NamedQuery(name = "MovieRating.findByRating", query = "SELECT r FROM MovieRating r WHERE r.rating=:rating")
})

public class MovieRating {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private int rating;
    
    private LocalDateTime created;

    public LocalDateTime getCreated() {
        return created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    @ManyToOne(targetEntity = Movie.class, cascade = CascadeType.PERSIST,fetch = FetchType.EAGER)
    private Movie movie;

    public MovieRating() {
    }

    public MovieRating(int rating, LocalDateTime created) {
        this.rating = rating;
        this.created = created;
    }


    

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRating() {
        return this.rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public Movie getMovie() {
        return this.movie;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
    }

    @Override
    public String toString() {
        return "rating=" + rating + "created=" + created;
    }



}