/**
 * This file was generated by the Jeddict
 */
package models;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

/**
 * @author Jonas
 */
@Entity

@NamedQueries({
@NamedQuery(name = "MovieGenre.findAll", query = "SELECT g FROM MovieGenre g"),
@NamedQuery(name = "MovieGenre.findById", query = "SELECT g FROM MovieGenre g WHERE g.id=:id"),
@NamedQuery(name = "MovieGenre.findByGenre", query = "SELECT g FROM MovieGenre g WHERE g.genre=:genre")
})

public class MovieGenre {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Basic
    private String genre;

    @ManyToMany(targetEntity = Movie.class, cascade = CascadeType.PERSIST,fetch = FetchType.EAGER)
    private List<Movie> movies = new ArrayList<>();

    public MovieGenre() {
    }

    public MovieGenre(String genre) {
        this.genre = genre;
    }

    
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGenre() {
        return this.genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public List<Movie> getMovies() {
        return this.movies;
    }

    public void setMovies(List<Movie> movies) {
        this.movies = movies;
    }

    @Override
    public String toString() {
        return "MovieGenre{" + "id=" + id + ", genre=" + genre + '}';
    }

        

}